### ISSUE TITLE
Can't start the server after install mod

### ISSUE THREAD

**Issue by wibucter** [Demomaker/BlockCounterMCModFabric#3] opened 2024-12-22 09:43 UTC
Log:
[16:41:40] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'blockcounter' at 'net.demomaker.blockcounter.main.BlockCounter'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.demomaker.blockcounter.main.BlockCounter.onInitialize(BlockCounter.java:28) ~[block-counter-1.3.3-for-minecraft-1.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	... 6 more

**Comment by wibucter** [comment] 2024-12-22 09:53
1.3.2 version works fine

**Comment by Demomaker** [comment] 2024-12-22 15:39
thank you for bringing this up. I will look into this

**Comment by Demomaker** [comment] 2024-12-22 17:24
I found the problem, it is supposed to be fixed in the latest release. Will wait for your feedback to be sure the issue is 100% resolved. https://github.com/Demomaker/BlockCounterMCModFabric/releases/tag/v1.3.4

**Comment by wibucter** [comment] 2024-12-23 02:51
> I found the problem, it is supposed to be fixed in the latest release. Will wait for your feedback to be sure the issue is 100% resolved. https://github.com/Demomaker/BlockCounterMCModFabric/releases/tag/v1.3.4

ok works fine

**Comment by Demomaker** [comment] 2024-12-23 03:30
Good! thanks for the response. I will close the issue now

**Closed as completed by Demomaker** 2024-12-23 03:30 UTC
